//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assimalign.OGraph.Gdm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assimalign.OGraph.Gdm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred..
        /// </summary>
        internal static string GDM0000 {
            get {
                return ResourceManager.GetString("GDM0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key disallowed. Complex types cannot have a key..
        /// </summary>
        internal static string GDM0301 {
            get {
                return ResourceManager.GetString("GDM0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key defined. A key is required for an entity type..
        /// </summary>
        internal static string GDM0401 {
            get {
                return ResourceManager.GetString("GDM0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type reference error. Only Entity Types can be referenced on vertices..
        /// </summary>
        internal static string GDM1001 {
            get {
                return ResourceManager.GetString("GDM1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type reference error. Type reference cannot be null..
        /// </summary>
        internal static string GDM1002 {
            get {
                return ResourceManager.GetString("GDM1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content error. Unexpected value disallowed..
        /// </summary>
        internal static string GDM3001 {
            get {
                return ResourceManager.GetString("GDM3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid label. Allowed characters: [a-z, A-Z, 0-9, _, @]..
        /// </summary>
        internal static string GDM5001 {
            get {
                return ResourceManager.GetString("GDM5001", resourceCulture);
            }
        }
    }
}
