name: assimalign.ograph.client.ci

on:
  push:
    branches:
    - main
    - development
    paths: 
    - 'Directory.Build.props'                                     # When the Global Props File Changes
    - 'libraries/Client/src/**'
    - '.github/workflows/assimalign.ograph.client.yml'        # When Pipeline File Changes

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2    
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'
        include-prerelease: true

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'
        include-prerelease: true
    
    - name: Restore Project
      run: dotnet restore 
      working-directory: './libraries/Client/src/Assimalign.OGraph.Client'
    
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
      working-directory: './libraries/Client/src/Assimalign.OGraph.Client'

    - name: Restore Unit Tests Project
      run: dotnet restore 
      working-directory: './libraries/Client/tests/Assimalign.OGraph.Client.Tests'

    - name: Run Unit Tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: './libraries/Client/tests/Assimalign.OGraph.Client.Tests'
    
    - name: Publish Nuget Package
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_PUBLISHING_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './libraries/Client/src/Assimalign.OGraph.Client/bin/Release/'